version: '3'
services:
  # mysqlcon1:
  #   image: mysql
  #   ports:
  #     - 3308:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD
  #   volumes:
  #     - ./mysql-data:/var/lib/mysql
  flask1con:
    image: flask1:6
    ports: 
      - 5001:5001
    links:
      - mysqlcon1
volumes:
  mysql-data: